/*
 * Roark Analytics API
 *
 * # Roark Analytics API - Voice AI Analytics Platform  The Roark Analytics API provides comprehensive monitoring, evaluation, and analytics capabilities for voice AI agents. This API allows developers to seamlessly integrate with the Roark platform to track call quality, analyze agent performance, and extract insights from voice interactions.  ## Key Features  - **Real-time Call Analysis**: Upload and analyze voice call recordings with AI-powered insights - **Sentiment Analysis**: Extract emotional tone, key phrases, and sentiment scores across 64+ emotions - **Agent Performance Evaluation**: Create custom evaluation jobs with configurable metrics and scoring - **Platform Integrations**: Native support for VAPI and Retell AI with webhook-based data ingestion - **Custom Analytics**: Build custom analytics pipelines with flexible data models and properties  ## Authentication  All API endpoints require Bearer token authentication. Include your API token in the Authorization header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Rate Limiting  The API implements rate limiting to ensure service stability. Rate limit headers are included in responses.  ## Error Handling  The API uses standard HTTP status codes and returns structured error responses with detailed error information including error types, codes, and human-readable messages.  ## Rust Code Generation  This OpenAPI specification has been optimized for Rust code generation with: - Snake_case field naming conventions - Proper nullable field handling with Option<T> - Comprehensive documentation for generated code - Type-safe enum definitions - Structured error handling
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@roark.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CallEndedStatus : High-level call termination status indicating how the call ended: - agent_ended_call: Agent terminated the call normally - agent_transferred_call: Agent transferred the call to another party - agent_error: Call ended due to agent system error - customer_ended_call: Customer hung up or terminated the call - voice_mail_reached: Call went to voicemail - silence_time_out: Call ended due to prolonged silence - phone_call_provider_connection_error: Telephony provider connection failure - customer_did_not_answer: Customer did not pick up the call - customer_busy: Customer line was busy - dial_error: Error occurred during dialing - max_duration_reached: Call reached maximum allowed duration - unknown: Call termination reason unknown
/// High-level call termination status indicating how the call ended: - agent_ended_call: Agent terminated the call normally - agent_transferred_call: Agent transferred the call to another party - agent_error: Call ended due to agent system error - customer_ended_call: Customer hung up or terminated the call - voice_mail_reached: Call went to voicemail - silence_time_out: Call ended due to prolonged silence - phone_call_provider_connection_error: Telephony provider connection failure - customer_did_not_answer: Customer did not pick up the call - customer_busy: Customer line was busy - dial_error: Error occurred during dialing - max_duration_reached: Call reached maximum allowed duration - unknown: Call termination reason unknown
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CallEndedStatus {
    #[serde(rename = "agent_ended_call")]
    AgentEndedCall,
    #[serde(rename = "agent_transferred_call")]
    AgentTransferredCall,
    #[serde(rename = "agent_error")]
    AgentError,
    #[serde(rename = "customer_ended_call")]
    CustomerEndedCall,
    #[serde(rename = "voice_mail_reached")]
    VoiceMailReached,
    #[serde(rename = "silence_time_out")]
    SilenceTimeOut,
    #[serde(rename = "phone_call_provider_connection_error")]
    PhoneCallProviderConnectionError,
    #[serde(rename = "customer_did_not_answer")]
    CustomerDidNotAnswer,
    #[serde(rename = "customer_busy")]
    CustomerBusy,
    #[serde(rename = "dial_error")]
    DialError,
    #[serde(rename = "max_duration_reached")]
    MaxDurationReached,
    #[serde(rename = "unknown")]
    Unknown,

}

impl std::fmt::Display for CallEndedStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AgentEndedCall => write!(f, "agent_ended_call"),
            Self::AgentTransferredCall => write!(f, "agent_transferred_call"),
            Self::AgentError => write!(f, "agent_error"),
            Self::CustomerEndedCall => write!(f, "customer_ended_call"),
            Self::VoiceMailReached => write!(f, "voice_mail_reached"),
            Self::SilenceTimeOut => write!(f, "silence_time_out"),
            Self::PhoneCallProviderConnectionError => write!(f, "phone_call_provider_connection_error"),
            Self::CustomerDidNotAnswer => write!(f, "customer_did_not_answer"),
            Self::CustomerBusy => write!(f, "customer_busy"),
            Self::DialError => write!(f, "dial_error"),
            Self::MaxDurationReached => write!(f, "max_duration_reached"),
            Self::Unknown => write!(f, "unknown"),
        }
    }
}

impl Default for CallEndedStatus {
    fn default() -> CallEndedStatus {
        Self::AgentEndedCall
    }
}

