/*
 * Roark Analytics API
 *
 * # Roark Analytics API - Voice AI Analytics Platform  The Roark Analytics API provides comprehensive monitoring, evaluation, and analytics capabilities for voice AI agents. This API allows developers to seamlessly integrate with the Roark platform to track call quality, analyze agent performance, and extract insights from voice interactions.  ## Key Features  - **Real-time Call Analysis**: Upload and analyze voice call recordings with AI-powered insights - **Sentiment Analysis**: Extract emotional tone, key phrases, and sentiment scores across 64+ emotions - **Agent Performance Evaluation**: Create custom evaluation jobs with configurable metrics and scoring - **Platform Integrations**: Native support for VAPI and Retell AI with webhook-based data ingestion - **Custom Analytics**: Build custom analytics pipelines with flexible data models and properties  ## Authentication  All API endpoints require Bearer token authentication. Include your API token in the Authorization header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Rate Limiting  The API implements rate limiting to ensure service stability. Rate limit headers are included in responses.  ## Error Handling  The API uses standard HTTP status codes and returns structured error responses with detailed error information including error types, codes, and human-readable messages.  ## Rust Code Generation  This OpenAPI specification has been optimized for Rust code generation with: - Snake_case field naming conventions - Proper nullable field handling with Option<T> - Comprehensive documentation for generated code - Type-safe enum definitions - Structured error handling
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@roark.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SentimentAnalysis : Sentiment analysis results for a call
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SentimentAnalysis {
    /// Status of the sentiment analysis job
    #[serde(rename = "status")]
    pub status: String,
    /// Average sentiment score across the entire call (0-1, where 1 is most positive)
    #[serde(rename = "average_sentiment", skip_serializing_if = "Option::is_none")]
    pub average_sentiment: Option<f64>,
    #[serde(rename = "average_categorical_sentiment", skip_serializing_if = "Option::is_none")]
    pub average_categorical_sentiment: Option<models::SentimentCategory>,
    /// Most frequently detected emotion throughout the call
    #[serde(rename = "common_emotion", skip_serializing_if = "Option::is_none")]
    pub common_emotion: Option<String>,
    /// Detailed breakdown of emotions detected with their frequencies
    #[serde(rename = "emotion_breakdown", skip_serializing_if = "Option::is_none")]
    pub emotion_breakdown: Option<std::collections::HashMap<String, f64>>,
}

impl SentimentAnalysis {
    /// Sentiment analysis results for a call
    pub fn new(status: String) -> SentimentAnalysis {
        SentimentAnalysis {
            status,
            average_sentiment: None,
            average_categorical_sentiment: None,
            common_emotion: None,
            emotion_breakdown: None,
        }
    }
}

