/*
 * Roark Analytics API
 *
 * # Roark Analytics API - Voice AI Analytics Platform  The Roark Analytics API provides comprehensive monitoring, evaluation, and analytics capabilities for voice AI agents. This API allows developers to seamlessly integrate with the Roark platform to track call quality, analyze agent performance, and extract insights from voice interactions.  ## Key Features  - **Real-time Call Analysis**: Upload and analyze voice call recordings with AI-powered insights - **Sentiment Analysis**: Extract emotional tone, key phrases, and sentiment scores across 64+ emotions - **Agent Performance Evaluation**: Create custom evaluation jobs with configurable metrics and scoring - **Platform Integrations**: Native support for VAPI and Retell AI with webhook-based data ingestion - **Custom Analytics**: Build custom analytics pipelines with flexible data models and properties  ## Authentication  All API endpoints require Bearer token authentication. Include your API token in the Authorization header:  ``` Authorization: Bearer YOUR_API_TOKEN ```  ## Rate Limiting  The API implements rate limiting to ensure service stability. Rate limit headers are included in responses.  ## Error Handling  The API uses standard HTTP status codes and returns structured error responses with detailed error information including error types, codes, and human-readable messages.  ## Rust Code Generation  This OpenAPI specification has been optimized for Rust code generation with: - Snake_case field naming conventions - Proper nullable field handling with Option<T> - Comprehensive documentation for generated code - Type-safe enum definitions - Structured error handling
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@roark.ai
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ToolInvocation : Details of a tool or function invocation during a call
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ToolInvocation {
    /// Name identifier of the invoked tool or function
    #[serde(rename = "name")]
    pub name: String,
    /// Human-readable description of the tool's purpose
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Parameters provided to the tool during invocation
    #[serde(rename = "parameters")]
    pub parameters: std::collections::HashMap<String, models::ToolInvocationParametersValue>,
    #[serde(rename = "result")]
    pub result: models::ToolInvocationResult,
    /// Offset in milliseconds from call start when tool was invoked
    #[serde(rename = "start_offset_ms")]
    pub start_offset_ms: u32,
    /// Offset in milliseconds from call start when tool execution completed
    #[serde(rename = "end_offset_ms", skip_serializing_if = "Option::is_none")]
    pub end_offset_ms: Option<u32>,
}

impl ToolInvocation {
    /// Details of a tool or function invocation during a call
    pub fn new(name: String, parameters: std::collections::HashMap<String, models::ToolInvocationParametersValue>, result: models::ToolInvocationResult, start_offset_ms: u32) -> ToolInvocation {
        ToolInvocation {
            name,
            description: None,
            parameters,
            result,
            start_offset_ms,
            end_offset_ms: None,
        }
    }
}

